"""A basic calculator.

Attributes:
    calc (browser.html.TABLE): The calculator.

"""

__all__ = ['calc', 'action']

from browser import document, html # pylint: disable=import-error

calc = html.TABLE(id='calc')
calc.attach(html.TR(html.TH(
    html.DIV("0", id="result"), colspan=3) + html.TD("C", id="clear")
))
calc.attach([
    html.TR(html.TD(x) for x in line)
    for line in ["789/", "456*", "123-", "0.=+"]
])

def action(event):
    """Handles the "click" event on a button of the calculator.

    Args:
        event (browser.DOMEvent): The event generated by clicking on a
            calculator button. The `target` attribute is the button that
            was clicked (which is an `html.TD` object).

    """
    value = event.target.text
    result = document["result"]
    if value not in "=C":
        if result.text in ["0", "error"]:
            result.text = value
        else:
            result.text = result.text + value
    elif value == "C":
        result.text = "0"
    elif value == "=":
        try:
            result.text = eval(result.text) # pylint: disable=eval-used
        except Exception as ex: # pylint: disable=broad-except
            print(ex)
            result.text = "error"

if __name__ == '__main__':
    document.attach(calc)
    for button in document.select("td"):
        button.bind("click", action)
